export const EXIT_CODES = {
  success: 0,
  generalFailure: 1,
  usageError: 2,
  sourceResolutionFailed: 4,
  bundleVerificationFailed: 5,
  validationFailed: 6,
  compatibilityFailed: 7,
  fileConflictBlocked: 8,
  filesystemApplyFailed: 9
} as const;

export const MINIMAL_FACTORY_REQUIRED_FILES = [
  "README.md",
  "QUICKSTART.md",
  "factory.json",
  "agents/orchestrator/PROMPT.md",
  "agents/orchestrator/AGENT.md",
  "agents/orchestrator/agent.json",
  "workflows/intake-existing-code/WORKFLOW.md",
  "workflows/intake-existing-code/workflow.json",
  "skills/handoff/SKILL.md",
  "skills/handoff/skill.json",
  "policies/security-policy.md",
  "policies/logging-policy.md",
  "policies/github-cli-policy.md",
  "policies/path-scopes.md",
  "schemas/factory.schema.json",
  "schemas/agent.schema.json",
  "schemas/workflow.schema.json",
  "schemas/skill.schema.json",
  "schemas/lockfile.schema.json",
  "templates/init-report.md",
  "templates/source-resolution-report.md",
  "templates/validation-report.md",
  "templates/compatibility-report.md",
  "templates/lockfile-report.md",
  "templates/conflicts.md",
  "templates/apply-plan.md"
] as const;

export const MINIMAL_FACTORY_JSON_FILES = [
  "factory.json",
  "agents/orchestrator/agent.json",
  "workflows/intake-existing-code/workflow.json",
  "skills/handoff/skill.json",
  "schemas/factory.schema.json",
  "schemas/agent.schema.json",
  "schemas/workflow.schema.json",
  "schemas/skill.schema.json",
  "schemas/lockfile.schema.json"
] as const;

export const FULL_FACTORY_REQUIRED_FILES = [
  "docs/FACTORY_PROFILE.md",
  "docs/AGENTS.md",
  "docs/WORKFLOW_CATALOG.md",
  "docs/SKILL_CATALOG.md",
  "agents/intake-agent/AGENT.md",
  "agents/intake-agent/agent.json",
  "agents/software-architect/AGENT.md",
  "agents/software-architect/agent.json",
  "agents/planner-agent/AGENT.md",
  "agents/planner-agent/agent.json",
  "agents/implementer-agent/AGENT.md",
  "agents/implementer-agent/agent.json",
  "agents/verifier-agent/AGENT.md",
  "agents/verifier-agent/agent.json",
  "workflows/ideation-from-zero/WORKFLOW.md",
  "workflows/ideation-from-zero/workflow.json",
  "workflows/architecture-ddd/WORKFLOW.md",
  "workflows/architecture-ddd/workflow.json",
  "workflows/tdd-implementation/WORKFLOW.md",
  "workflows/tdd-implementation/workflow.json",
  "workflows/verification-pr/WORKFLOW.md",
  "workflows/verification-pr/workflow.json",
  "skills/sdd-requirements/SKILL.md",
  "skills/sdd-requirements/skill.json",
  "skills/backlog-planning/SKILL.md",
  "skills/backlog-planning/skill.json",
  "skills/github-actions-cicd/SKILL.md",
  "skills/github-actions-cicd/skill.json",
  "skills/github-cli/SKILL.md",
  "skills/github-cli/skill.json",
  "skills/github-issue-publisher/SKILL.md",
  "skills/github-issue-publisher/skill.json",
  "skills/github-issue-discovery/SKILL.md",
  "skills/github-issue-discovery/skill.json",
  "skills/html-architecture-diagrams/SKILL.md",
  "skills/html-architecture-diagrams/skill.json",
  "skills/diagnose-bug/SKILL.md",
  "skills/diagnose-bug/skill.json",
  "skills/gridwork-release-publisher/SKILL.md",
  "skills/gridwork-release-publisher/skill.json",
  "skills/tdd/SKILL.md",
  "skills/tdd/skill.json",
  "skills/git-branch-management/SKILL.md",
  "skills/git-branch-management/skill.json",
  "skills/github-label-manager/SKILL.md",
  "skills/github-label-manager/skill.json",
  "policies/agent-permissions.md",
  "policies/workspace-domains.md",
  "policies/human-gates.md",
  "policies/policy-precedence.md",
  "policies/security-secrets-redaction.md",
  "policies/github-labels.json",
  "policies/tdd-evidence-policy.md",
  "policies/git-policy.md",
  "policies/work-order-policy.md",
  "policies/tool-allowlist.md",
  "templates/work-order-afk.md",
  "templates/run-summary.md",
  "templates/run-state.json",
  "templates/event.jsonl",
  "templates/metrics.json",
  "templates/tdd-evidence.md",
  "templates/verifier-report.md",
  "templates/github-pr-comment.md",
  "templates/handoff.md",
  "templates/github-issue-draft.md",
  "templates/github-issue-publish-plan.md",
  "templates/tdd-plan.md",
  "templates/implementation-summary.md",
  "templates/git-action-plan.md",
  "templates/github-label-plan.md",
  "stack-packs/nextjs-springboot-postgresql/stack-pack.json",
  "stack-packs/nextjs-springboot-postgresql/STACK.md",
  "stack-packs/nextjs-springboot-postgresql/README.md",
  "stack-packs/nextjs-springboot-postgresql/policies/test-commands.json",
  "stack-packs/nextjs-springboot-postgresql/policies/quality-commands.json",
  "stack-packs/nextjs-springboot-postgresql/policies/path-hints.md",
  "stack-packs/nextjs-springboot-postgresql/policies/vertical-slice-policy.md",
  "stack-packs/nextjs-springboot-postgresql/policies/ddd-stack-guidance.md",
  "stack-packs/nextjs-springboot-postgresql/policies/docker-compose-guidance.md",
  "stack-packs/nextjs-springboot-postgresql/templates/github-issue-fullstack-slice.md",
  "stack-packs/nextjs-springboot-postgresql/templates/work-order-fullstack-slice.md",
  "stack-packs/nextjs-springboot-postgresql/templates/test-plan-fullstack-slice.md",
  "stack-packs/nextjs-springboot-postgresql/templates/api-contract.md",
  "stack-packs/nextjs-springboot-postgresql/templates/database-migration-plan.md",
  "stack-packs/nextjs-springboot-postgresql/skills/nextjs-frontend-guidance/SKILL.md",
  "stack-packs/nextjs-springboot-postgresql/skills/nextjs-frontend-guidance/skill.json",
  "stack-packs/nextjs-springboot-postgresql/skills/springboot-backend-guidance/SKILL.md",
  "stack-packs/nextjs-springboot-postgresql/skills/springboot-backend-guidance/skill.json",
  "stack-packs/nextjs-springboot-postgresql/skills/postgresql-persistence-guidance/SKILL.md",
  "stack-packs/nextjs-springboot-postgresql/skills/postgresql-persistence-guidance/skill.json",
  "stack-packs/nextjs-springboot-postgresql/skills/docker-compose-local-guidance/SKILL.md",
  "stack-packs/nextjs-springboot-postgresql/skills/docker-compose-local-guidance/skill.json"
] as const;

export const FULL_FACTORY_JSON_FILES = [
  "agents/intake-agent/agent.json",
  "agents/software-architect/agent.json",
  "agents/planner-agent/agent.json",
  "agents/implementer-agent/agent.json",
  "agents/verifier-agent/agent.json",
  "workflows/ideation-from-zero/workflow.json",
  "workflows/architecture-ddd/workflow.json",
  "workflows/tdd-implementation/workflow.json",
  "workflows/verification-pr/workflow.json",
  "skills/sdd-requirements/skill.json",
  "skills/backlog-planning/skill.json",
  "skills/github-actions-cicd/skill.json",
  "skills/github-cli/skill.json",
  "skills/github-issue-publisher/skill.json",
  "skills/github-issue-discovery/skill.json",
  "skills/html-architecture-diagrams/skill.json",
  "skills/diagnose-bug/skill.json",
  "skills/gridwork-release-publisher/skill.json",
  "skills/tdd/skill.json",
  "skills/git-branch-management/skill.json",
  "skills/github-label-manager/skill.json",
  "policies/github-labels.json",
  "templates/run-state.json",
  "templates/metrics.json",
  "stack-packs/nextjs-springboot-postgresql/stack-pack.json",
  "stack-packs/nextjs-springboot-postgresql/policies/test-commands.json",
  "stack-packs/nextjs-springboot-postgresql/policies/quality-commands.json",
  "stack-packs/nextjs-springboot-postgresql/skills/nextjs-frontend-guidance/skill.json",
  "stack-packs/nextjs-springboot-postgresql/skills/springboot-backend-guidance/skill.json",
  "stack-packs/nextjs-springboot-postgresql/skills/postgresql-persistence-guidance/skill.json",
  "stack-packs/nextjs-springboot-postgresql/skills/docker-compose-local-guidance/skill.json"
] as const;

export const FORBIDDEN_PRODUCT_PATHS = [
  "frontend",
  "backend",
  "database",
  "docker",
  "docker-compose.yml"
] as const;

export const LOCKFILE_PATH = ".gridwork-lock.json";
export const FACTORY_SOURCE_LABEL = "factory/.gridwork";
export const INSTALLER_PACKAGE_NAME = "gridwork";
export const INSTALLER_VERSION = "0.1.0";
export const PLACEHOLDER_FACTORY_SOURCE = "gridwork/gridwork";
export const DEFAULT_FACTORY_SOURCE = "Ainsiel/Gridwork";
export const FACTORY_TAG_PREFIX = "factory-v";
